CREATE TABLE IF NOT EXISTS `pet_outfit` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `user_id` BIGINT NOT NULL,
    `head` VARCHAR(50) DEFAULT NULL,
    `face` VARCHAR(50) DEFAULT NULL,
    `neck` VARCHAR(50) DEFAULT NULL,
    `body` VARCHAR(50) DEFAULT NULL,
    `accessory` VARCHAR(50) DEFAULT NULL,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY `uk_user_id` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
